apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config-1
  namespace: digdag-jobs
data:
  example.property.1: hello
  example.property.2: world
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pi-1
  namespace: digdag-jobs
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pi-2
  namespace: digdag-jobs
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config-2
  namespace: digdag-jobs
data:
  example.property.1: hello
  example.property.2: world
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config-3
  namespace: digdag-jobs
data:
  example.property.1: hello
  example.property.2: worldcd
